rootProject.name = "FoodDeliveryApplication"
include("api-gateway")
include("auth-service")
include("delivery-service")
include("order-service")
include("restaurant-service")
include("payment-service")
include("discovery-service")
include("delivery-service")
include("External-Contracts")