server.port=8084
spring.application.name=payment-service
spring.data.mongodb.uri=mongodb://localhost:27017/paymentdb

# kafka serializers :
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
